"""Build LaTeX snippets for the BookTrendsRecSys technical report."""
from __future__ import annotations

import csv
import json
import math
from pathlib import Path
from typing import Dict, List, Tuple


def latex_escape(text: str) -> str:
    """Escape LaTeX special characters in text."""
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    result = text
    for old, new in replacements.items():
        result = result.replace(old, new)
    return result


def ensure_auto_dir(auto_dir: Path) -> None:
    auto_dir.mkdir(parents=True, exist_ok=True)


def load_json(path: Path) -> Dict:
    try:
        with path.open("r", encoding="utf-8") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


def load_csv_rows(path: Path) -> Tuple[List[str], List[Dict[str, str]]]:
    try:
        with path.open("r", encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            rows = [row for row in reader]
            return reader.fieldnames or [], rows
    except FileNotFoundError:
        return [], []


def format_percent(value: float | None) -> str:
    if value is None:
        return "N/A"
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return "N/A"
    if math.isnan(numeric):
        return "N/A"
    if numeric > 1.0 + 1e-6:
        percent = numeric
    else:
        percent = numeric * 100.0
    return f"{percent:.1f}\\%"


def format_number(value: float | int | None) -> str:
    if value is None:
        return "N/A"
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return latex_escape(str(value))
    if numeric.is_integer():
        return f"{int(numeric)}"
    return f"{numeric:.3g}"


def write_numbers(auto_dir: Path, metrics: Dict, parity_gap: str, metrics_available: bool, parity_available: bool, data_available: bool) -> None:
    params = metrics.get("params", {}) if isinstance(metrics, dict) else {}
    p10 = metrics.get("p10") if isinstance(metrics, dict) else None
    r10 = metrics.get("r10") if isinstance(metrics, dict) else None
    ndcg10 = metrics.get("ndcg10") if isinstance(metrics, dict) else None

    numbers_lines = [
        "% Auto-generated by build_report_assets.py",
        f"\\newcommand{{\\pTen}}{{{format_percent(p10)}}}",
        f"\\newcommand{{\\rTen}}{{{format_percent(r10)}}}",
        f"\\newcommand{{\\ndcgTen}}{{{format_percent(ndcg10)}}}",
        f"\\newcommand{{\\rankParam}}{{{format_number(params.get('rank'))}}}",
        f"\\newcommand{{\\regParam}}{{{format_number(params.get('reg'))}}}",
        f"\\newcommand{{\\alphaParam}}{{{format_number(params.get('alpha'))}}}",
        f"\\newcommand{{\\itersParam}}{{{format_number(params.get('iters'))}}}",
        f"\\newcommand{{\\parityGap}}{{{parity_gap}}}",
    ]

    metrics_note = "" if metrics_available else r"\par\smallskip\textit{Metrics were unavailable at build time; rerun \texttt{make eval}.}"
    parity_note = "" if parity_available else r"\par\smallskip\textit{Fairness diagnostics were unavailable; rerun \texttt{make parity}.}"
    data_note = "" if data_available else r"\par\smallskip\textit{Data summaries were unavailable; rerun \texttt{make data}.}"

    numbers_lines.extend(
        [
            f"\\newcommand{{\\metricsStatusNote}}{{{metrics_note}}}",
            f"\\newcommand{{\\parityStatusNote}}{{{parity_note}}}",
            f"\\newcommand{{\\dataStatusNote}}{{{data_note}}}",
        ]
    )

    (auto_dir / "numbers.tex").write_text("\n".join(numbers_lines) + "\n", encoding="utf-8")


def write_metrics_table(auto_dir: Path, metrics: Dict) -> bool:
    table_path = auto_dir / "metrics_table.tex"
    if not isinstance(metrics, dict) or not metrics:
        lines = [
            "% Auto-generated metrics table (fallback)",
            "\\begin{tabular}{ll}",
            "\\toprule",
            "Metric & Value \\",
            "\\midrule",
            "P@10 & N/A \\",
            "R@10 & N/A \\",
            "NDCG@10 & N/A \\",
            "Rank & N/A \\",
            "Reg & N/A \\",
            "Alpha & N/A \\",
            "Iters & N/A \\",
            "\\bottomrule",
            "\\end{tabular}",
        ]
        table_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return False

    params = metrics.get("params", {}) if isinstance(metrics.get("params"), dict) else {}
    rows = [
        ("P@10", format_percent(metrics.get("p10"))),
        ("R@10", format_percent(metrics.get("r10"))),
        ("NDCG@10", format_percent(metrics.get("ndcg10"))),
        ("Rank", format_number(params.get("rank"))),
        ("Reg", format_number(params.get("reg"))),
        ("Alpha", format_number(params.get("alpha"))),
        ("Iters", format_number(params.get("iters"))),
    ]
    lines = ["% Auto-generated metrics table", "\\begin{tabular}{ll}", "\\toprule", "Metric & Value \\", "\\midrule"]
    for key, value in rows:
        lines.append(f"{latex_escape(key)} & {value} \\")
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    table_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return True


def compute_parity(auto_dir: Path, parity_csv: Path) -> Tuple[str, bool]:
    headers, rows = load_csv_rows(parity_csv)
    if not rows:
        lines = [
            "% Auto-generated parity table (fallback)",
            "\\begin{tabular}{ll}",
            "\\toprule",
            "Group & NDCG@10 \\",
            "\\midrule",
            "N/A & N/A \\",
            "\\bottomrule",
            "\\end{tabular}",
        ]
        (auto_dir / "parity_table.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
        return "N/A", False

    metric_rows = rows
    if any(row.get("metric") == "ndcg10" for row in rows):
        metric_rows = [row for row in rows if row.get("metric") == "ndcg10"]

    aggregates: Dict[str, List[float]] = {}
    for row in metric_rows:
        try:
            value = float(row.get("value", "nan"))
        except ValueError:
            continue
        if math.isnan(value):
            continue
        group = row.get("group", "group")
        group_value = row.get("group_value", "value")
        label = f"{group}: {group_value}"
        aggregates.setdefault(label, []).append(value)

    if not aggregates:
        lines = [
            "% Auto-generated parity table (no valid values)",
            "\\begin{tabular}{ll}",
            "\\toprule",
            "Group & NDCG@10 \\",
            "\\midrule",
            "N/A & N/A \\",
            "\\bottomrule",
            "\\end{tabular}",
        ]
        (auto_dir / "parity_table.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
        return "N/A", False

    averages: List[Tuple[str, float]] = []
    for label, values in aggregates.items():
        avg = sum(values) / len(values)
        averages.append((label, avg))

    averages.sort(key=lambda item: item[1], reverse=True)
    values_only = [value for _, value in averages]
    max_val = max(values_only)
    min_val = min(values_only)
    gap = (max_val - min_val) * (100.0 if max_val <= 1.0 + 1e-6 else 1.0)
    gap_math = f"\\ensuremath{{{gap:.1f}\\,\\mathrm{{pp}}}}"

    lines = ["% Auto-generated parity table", "\\begin{tabular}{ll}", "\\toprule", "Group & NDCG@10 \\", "\\midrule"]
    for label, value in averages:
        percent = format_percent(value)
        lines.append(f"{latex_escape(label)} & {percent} \\")
    lines.append("\\midrule")
    lines.append(f"\\multicolumn{{2}}{{l}}{{gap = {gap_math}}} \\")
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    (auto_dir / "parity_table.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return gap_math, True


def build_eda_table(auto_dir: Path, eda_json: Path) -> bool:
    eda_data = load_json(eda_json)
    rows: List[Tuple[str, str]] = []
    if eda_data:
        for key in [
            "n_books",
            "n_users",
            "n_interactions",
            "sparsity",
            "top_languages",
            "year_span",
        ]:
            if key in eda_data:
                value = eda_data[key]
                if isinstance(value, (list, tuple)):
                    value_text = ", ".join(str(v) for v in value)
                else:
                    value_text = str(value)
                rows.append((key.replace("_", " ").title(), latex_escape(value_text)))
    if not rows:
        lines = [
            "% Auto-generated EDA table (fallback)",
            "\\begin{tabular}{ll}",
            "\\toprule",
            "Statistic & Value \\",
            "\\midrule",
            "N/A & N/A \\",
            "\\bottomrule",
            "\\end{tabular}",
        ]
        (auto_dir / "eda_summary_table.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
        return False

    lines = ["% Auto-generated EDA table", "\\begin{tabular}{ll}", "\\toprule", "Statistic & Value \\", "\\midrule"]
    for label, value in rows:
        lines.append(f"{latex_escape(label)} & {value} \\")
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    (auto_dir / "eda_summary_table.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return True


def build_top_lists(auto_dir: Path, most_path: Path, cold_path: Path) -> None:
    most_headers, most_rows = load_csv_rows(most_path)
    cold_headers, cold_rows = load_csv_rows(cold_path)

    def pick_columns(headers: List[str]) -> Tuple[str, str | None]:
        if not headers:
            return ("Item", None)
        if "title" in headers and len(headers) > 1:
            return "title", headers[1]
        return headers[0], headers[1] if len(headers) > 1 else None

    most_col, most_val_col = pick_columns(most_headers)
    cold_col, cold_val_col = pick_columns(cold_headers)

    def format_rows(rows: List[Dict[str, str]], col: str, val_col: str | None) -> List[Tuple[str, str]]:
        formatted: List[Tuple[str, str]] = []
        for row in rows[:10]:
            name = latex_escape(row.get(col, "N/A"))
            val = row.get(val_col, "") if val_col else ""
            if val:
                formatted.append((name, latex_escape(str(val))))
            else:
                formatted.append((name, ""))
        return formatted

    most_entries = format_rows(most_rows, most_col, most_val_col) if most_rows else []
    cold_entries = format_rows(cold_rows, cold_col, cold_val_col) if cold_rows else []

    lines: List[str] = ["% Auto-generated top lists"]
    if most_entries or cold_entries:
        lines.append("\\begin{table}[h]")
        lines.append("    \\centering")
        lines.append("    \\caption{Top catalog insights from interaction logs.}")
        lines.append("    \\begin{subtable}[t]{0.48\\linewidth}")
        lines.append("        \\centering")
        lines.append("        \\caption{Most rated books}")
        lines.append("        \\begin{tabular}{ll}")
        lines.append("            \\toprule")
        lines.append("            Title & Stat \\")
        lines.append("            \\midrule")
        if most_entries:
            for title, value in most_entries:
                display_val = value or "--"
                lines.append(f"            {title} & {display_val} \\")
        else:
            lines.append("            N/A & N/A \\")
        lines.append("            \\bottomrule")
        lines.append("        \\end{tabular}")
        lines.append("    \\end{subtable}\\hfill")
        lines.append("    \\begin{subtable}[t]{0.48\\linewidth}")
        lines.append("        \\centering")
        lines.append("        \\caption{Cold-start attention}")
        lines.append("        \\begin{tabular}{ll}")
        lines.append("            \\toprule")
        lines.append("            Title & Stat \\")
        lines.append("            \\midrule")
        if cold_entries:
            for title, value in cold_entries:
                display_val = value or "--"
                lines.append(f"            {title} & {display_val} \\")
        else:
            lines.append("            N/A & N/A \\")
        lines.append("            \\bottomrule")
        lines.append("        \\end{tabular}")
        lines.append("    \\end{subtable}")
        lines.append("\\end{table}")
    else:
        lines.append(r"\begin{center}\textit{Top list summaries were unavailable.}\end{center}")

    (auto_dir / "top_lists.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    script_path = Path(__file__).resolve()
    auto_dir = script_path.parents[1] / "auto"
    ensure_auto_dir(auto_dir)

    repo_root = script_path.parents[4]

    metrics_path = repo_root / "metrics" / "metrics.json"
    parity_path = repo_root / "metrics" / "parity.csv"
    eda_path = repo_root / "data" / "processed" / "eda_summary.json"
    most_path = repo_root / "data" / "processed" / "top10_most_rated.csv"
    cold_path = repo_root / "data" / "processed" / "top10_cold_books.csv"

    metrics = load_json(metrics_path)
    metrics_available = write_metrics_table(auto_dir, metrics)

    parity_gap, parity_available = compute_parity(auto_dir, parity_path)

    data_available = build_eda_table(auto_dir, eda_path)
    build_top_lists(auto_dir, most_path, cold_path)

    write_numbers(auto_dir, metrics, parity_gap, metrics_available, parity_available, data_available)


if __name__ == "__main__":
    main()
